# Working with numpy arrays

In [2]:
import numpy as np

# ARRAYS

In [3]:
myList = [1, 2, 3, 4, 5, 6, 7]
myList
type(myList)

list

In [4]:
np.array(myList)

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
arr = np.array(myList)

In [8]:
type(arr)

numpy.ndarray

In [7]:
nested = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
type(nested)

list

In [9]:
np.array(nested)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
tup = (1, 2, 3, 4, 5)

In [11]:
type(tup)

tuple

In [12]:
np.array(tup)

array([1, 2, 3, 4, 5])

In [19]:
# creating numpy array using a set

set1 = {1, 2, 2, 3, 3, 4, 5, 6, 6, 6}

In [20]:
set1

{1, 2, 3, 4, 5, 6}

In [21]:
np.array(set1)

array({1, 2, 3, 4, 5, 6}, dtype=object)

In [22]:
type(np.array(set1))

numpy.ndarray

# Identity matrix

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
type(np.eye(5))

numpy.ndarray

In [25]:
list(range(20))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [26]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
type(np.arange(20))

numpy.ndarray

In [39]:
result = 0
for i in range(10000):
    result += i
print(result)

49995000


In [41]:
np.arange(10000).sum()

49995000

In [50]:
np.linspace(0, 5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [51]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
arr = np.array(nested)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
# checking attributes
arr.ndim

2

In [58]:
arr1 = np.array([1, 2, 3])
arr1.ndim

1

In [59]:
arr.size

9

In [60]:
arr.shape

(3, 3)

In [61]:
arr1.shape

(3,)

In [62]:
arr1.size

3

# Numpy boolean indexing

In [7]:
arr = np.arange(19)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [13]:
# filter elements based on a condition

arr<2

array([ True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [14]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [16]:
#boolean masking
arr[arr>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [18]:
arr1=np.random.randint(20, 40)
arr1

20

In [23]:
arr1=np.arange(40).reshape((5, 8))
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [26]:
arr1>10

array([[False, False, False, False, False, False, False, False],
       [False, False, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [27]:
arr1[arr1>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [34]:
# & means and while | means or

arr2= arr1[(arr1>10) & (arr1 <31)]
arr2.reshape((4, 5))

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [35]:
arr2.size

20

# Fancy indexing

In [44]:
list1=[2, 4, 1]

In [45]:
arr1[list1]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [48]:
arr1[list1] = 99
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [99, 99, 99, 99, 99, 99, 99, 99]])

In [49]:
arr1 == 99

array([[False, False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [51]:
arr1[arr1==99]

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99])

# Pandas series

In [58]:
#importing pandas

import pandas as pd

In [59]:
names = ["esther", "tochi", "amaka", "gift", "chalse"]
x = pd.Series(names)

In [60]:
type(arr1)

numpy.ndarray

In [61]:
x

0    esther
1     tochi
2     amaka
3      gift
4    chalse
dtype: object

In [63]:
# creating a series from a dictionary
dict = {"name": "Diana",
               "age": 22,
               "gender": "female",
               "country": "Ghana",
               "marital status": "single",
               "City": "Accra",
               "occupation": "data analyst"}

In [67]:
details = pd.Series(dict)

In [68]:
details

name                     Diana
age                         22
gender                  female
country                  Ghana
marital status          single
City                     Accra
occupation        data analyst
dtype: object